# Generated by Django 4.2.20 on 2025-04-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
